In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [6]:
b = [1, 2, 3]

In [4]:
a[1]

2

In [5]:
a[-1]

3

In [7]:
b

[1, 2, 3]

In [8]:
type(a)

numpy.ndarray

In [9]:
type(b)

list

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [12]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
print(np.arange(4))

[0 1 2 3]


In [14]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
arr = np.append(arr, [1,2])

In [22]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8, 1, 2])

In [23]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [24]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [30]:
arr_one

array([[1, 2, 3, 4, 5]])

In [31]:
arr_one.ndim

2

In [32]:
arr_one.size

5

In [33]:
arr_one.shape

(1, 5)

In [34]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [37]:
a.size

6

In [35]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [36]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
a.reshape(5,2)

ValueError: cannot reshape array of size 6 into shape (5,2)

In [39]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [41]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [42]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [43]:
data = np.array([1,2,3])

print(data) # [1, 2, 3]
print(data[0]) # 1
print(data[1]) # 2
print(data[0:2]) # 1, 2
print(data[1:]) # 2, 3
print(data[-2:]) # 2, 3

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [44]:
a = np.array([1, 2, 3, 4])

In [45]:
a.sum()

10

In [46]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [49]:
b.sum(axis = 1)

array([2, 4])

In [50]:
data = np.array([1, 2])
data

array([1, 2])

In [51]:
ones = np.ones(2)
ones

array([1., 1.])

In [52]:
data + ones

array([2., 3.])

In [53]:
data * data

array([1, 4])

In [54]:
data / data

array([1., 1.])

In [55]:
data * 2

array([2, 4])

In [57]:
data.max()

2

In [58]:
data.min()

1

In [59]:
data.sum()

3

In [60]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [61]:
A.sum()

4.8595784

In [62]:
A.min()

0.05093587

In [63]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [64]:
A.max()

0.82485143

In [65]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [66]:
A.std()

0.21392120766089617

In [69]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.random.random((3,2))

array([[0.26482363, 0.52429474],
       [0.5024687 , 0.0508862 ],
       [0.11224828, 0.34639711]])

In [72]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [73]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [74]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [75]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [76]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [77]:
data

array([[1, 2],
       [3, 4]])

In [78]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [79]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [80]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [84]:
print(data[1:3])

[[3 4]
 [5 6]]


In [81]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])